# 1.create a 5X5 array with numbers 1-25 , extract the middle 3X3 block .

In [1]:
import numpy as np

In [2]:
arr1=np.arange(1,26).reshape(5,5)
print(arr1)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]


In [3]:
print(arr1[0:3])

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]


# 2.create an array of10 numbers, replace all even numbers with -1.

In [4]:
arr2=np.arange(1,11)
print(arr2)
arr2[arr2 % 2 == 0] = -1
print(arr2)

[ 1  2  3  4  5  6  7  8  9 10]
[ 1 -1  3 -1  5 -1  7 -1  9 -1]


# 3. try broadcasting : add [1,2,3,4]to a 4X4 array.

In [6]:
arr3=np.arange(1,17).reshape(4,4)
print(arr3)


[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]


In [7]:
add=np.array([1,2,3,4])
print(arr3+add)

[[ 2  4  6  8]
 [ 6  8 10 12]
 [10 12 14 16]
 [14 16 18 20]]
